name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: aiplan4eu/upf

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Mypy check
        uses: jpetrucciani/mypy-check@master

      - name: Install Python dependencies
        run: python3 -mpip install -r requirements.txt

      - name: Install Development Python dependencies
        run: python3 -mpip install -r dev-requirements.txt

      - name: Install Pyperplan-upf and Tamer-upf
        run: pip install -e .[devs]

      - name: Download ENHSP
        run: |
          git clone https://gitlab.com/enricos83/ENHSP-Public.git
          cd ENHSP-Public; git checkout enhsp-20; ./compile; cd ..
          mkdir .planners; mv ENHSP-Public/enhsp-dist .planners/enhsp-20; rm -rf ENHSP-Public

      - name: Run tests
        run: bash run_tests.sh

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true
